### ISSUE TITLE
How to preprocess the data

### ISSUE THREAD

**Issue by minhngh** [leichainju/pa-former#3]
Dear Mr. Lei Chai:

Congrats on your great work. 
I saw that you released the source code along with the processed data used in the paper. 
However, I have not found necessary scripts which convert the raw data into the proper format in the paper. Specifically,  when I am in the _dataset_ folder, I saw some tutorials, but these do not work.
Would it be possible for you to release such scripts?

Thank you so much.

**Comment by leichainju** [comment]
Thanks for your attention, I will upload the pre-processing code ASAP.

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Minh&nbsp;Nguyen ***@***.***&gt;;
发送时间：2023年1月28日(星期六) 下午5:02
收件人："leichainju/pa-former" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[leichainju/pa-former] How to preprocess the data (Issue #3)
-----------------------------------

 

 
Dear Mr. Lei Chai:
 
Congrats on your great work.
 I saw that you released the source code along with the processed data used in the paper.
 However, I have not found necessary scripts which convert the raw data into the proper format in the paper. Specifically,  when I am in the dataset folder, I saw some tutorials, but these do not work.
 Would it be possible for you to release such scripts?
 
Thank you so much.

**Comment by minhngh** [comment]
Hi Mr. Lei Chai,

Could you release these pieces of code soon?

Thank you a lot.

**Comment by leichainju** [comment]
done
